import './globals.css';

export const metadata = {
	title: 'Crypto Website Project',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<link rel="shortcut icon" href="./icon.png" type="image/x-icon" />
			<body>{children}</body>
		</html>
	);
}
